### ISSUE TITLE
Regle de validation email

### ISSUE THREAD

**Issue by b1nj** [AxelRN/laravel-test-developpeur#9]
https://github.com/AxelRN/laravel-test-developpeur/blob/d72727230d8a7536b8e0bb6ad8bab38554df0f00/laravel-test-ARN/app/Http/Controllers/ContactController.php#L20

Il existe une règle spécial laravel pour tester les emails. La regex semble intéressante, mais ne prend peut être pas en compte toutes les possibilités d'une adresse email valide.

**Comment by AxelRN** [comment]
`'email' => 'email:rfc,dns'`

Je pense que vous parlez de cette règle mais elle ne semblais pas fonctionner.

Est-ce bien cela?

**Comment by b1nj** [comment]
Vous pouvez enlever "dns" qui demande l'extension php intl, comme indiqué dans la doc.
